[package]
name = "triad-data"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30"
serde = { version = "1.0", features = ["derive"] }
serde-ply = "0.2"
serde_json = "1.0"
delaunator = "1.0"
tracing = "0.1"
thiserror = "2.0"
